POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "My video",
    "description": "My video description",
    "duration": 120
}

###

GET http://localhost:3333/videos

###
